### ISSUE TITLE
Play Again

### ISSUE THREAD

**Issue by Laperst** [Apostolique/Agar.io-bot#312]
Hello i dunno how to set up play again option when they ate you then game stuck (is there option to automat press esc and play button) or can you add this to your awesome bot please?

**Comment by MrMaDCaT** [comment]
yea having same issue , this is since new update ;)

**Comment by the-casle** [comment]
same thing

**Comment by Apostolique** [comment]
Fixed?

**Comment by MrMaDCaT** [comment]
@Apostolique  no still the same , tested it in : 
[Maxthon(violentMonkey)still as 10mass and no xp]
[Opera(tamperMonkey)+(violentMonkey)Ok but not respawning or autostarting]
[Chrome(tamperMonkey)Ok but not respawning or autostarting]

**Comment by Laperst** [comment]
I am using chrome so bot is working well but that auto start is missing

**Comment by Laperst** [comment]
Its working on chrome when i using those double codes not that automatic updating but those manual 2 and now its autostarting well ty for you fast work :)

**Comment by MrMaDCaT** [comment]
aight i try that too thanks @Laperst  for the heads up ^^

**Comment by MrMaDCaT** [comment]
@Apostolique it only works with both files and not the autoloader !
Cheers for the nice coding !

**Comment by Apostolique** [comment]
Yeah, I'll have to look into it.

**Comment by Rise321** [comment]
@Apostolique mine isn't okay yet, the autostart or respawning isnt woking after the recent update. I use the 2 codes (aposbot and Aposlauncher) in Chrome browser, same with firefox.. It would be great to fix this issue.. anyway, waiting for your fix and thanks for your awesome bot!

**Comment by Rise321** [comment]
oh! it is ok now... i just logged out my account in facebook and login again and it solved my problem!

**Comment by Apostolique** [comment]
Nice! I'll close this issue then.
