### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#5]
I have set everything up right as far as i have read, but nothing happens. The script is enabled and everything.

**Comment by Apostolique** [comment]
After Agar.io got updated today, the script was left broken. Should be fixed now.

**Comment by DarkN3ss61** [comment]
Hi I still cant seem to get it working as shown here https://www.youtube.com/watch?v=z6ZPIQWCzdw

Any idea why?

**Comment by Apostolique** [comment]
Oh whoops, I didn't document this, you'll probably need to press T for the bot to work. If that still doesn't work, look into your console to see if the loading messages show up.

**Comment by DarkN3ss61** [comment]
ok i tried that and it still didnt work, i will make a new video now

**Comment by AshleyDodd** [comment]
Mine works, but the lines are not being drawn & it does not auto restart.

**Comment by Apostolique** [comment]
I forgot the add the auto restart back in. I guess that's what happens when you try to fix stuff quickly Kappa.

**Comment by DarkN3ss61** [comment]
Ok here is the video of it not working https://www.youtube.com/watch?v=Vsqocq27KVQ
any idea why this is?

**Comment by Apostolique** [comment]
It looks like the script is not running at all. This is likely caused by an error in the script. I don't have that error for some reason. Here is what you should try: remove everything that is inside function main_out() { /*remove all the stuff in here*/ }

Then check your console to see if the loading script is running.

**Comment by DarkN3ss61** [comment]
Ok, also if you want to i can give you TeamViewer access to my computer if you want to try debug whats going on?

**Comment by Apostolique** [comment]
I wouldn't mind helping that way, but it kind of sucks to have to resort to that.

**Comment by DarkN3ss61** [comment]
My output is this:
===============================
The connection to ws://45.56.91.201:443/ was interrupted while the page was loading. main_out.js:2
GET http://agar.io/ [HTTP/1.1 304 Not Modified 460ms]
"socket close" main_out.js:2
Use of getUserData() or setUserData() is deprecated.  Use WeakMap or element.dataset instead. requestNotifier.js:64
GET http://fonts.googleapis.com/css [HTTP/1.1 200 OK 329ms]
GET http://agar.io/css/bootstrap.min.css [HTTP/1.1 304 Not Modified 36ms]
GET http://static.addtoany.com/menu/page.js [HTTP/1.1 304 Not Modified 450ms]
GET http://agar.io/js/jquery.js [HTTP/1.1 304 Not Modified 341ms]
GET http://agar.io/quadtree.js [HTTP/1.1 304 Not Modified 341ms]
GET http://agar.io/main_out.js [HTTP/1.1 304 Not Modified 344ms]
GET http://ajax.cloudflare.com/cdn-cgi/nexp/dok3v=7e13c32551/cloudflare.min.js [HTTP/1.1 304 Not Modified 361ms]
GET http://agar.io/blocker.png [HTTP/1.1 304 Not Modified 30ms]
GET http://agar.io/img/split.png [HTTP/1.1 304 Not Modified 34ms]
GET http://www.google-analytics.com/analytics.js [HTTP/1.1 304 Not Modified 7ms]
GET http://static.addtoany.com/menu/svg/icons.12.svg.css [HTTP/1.1 304 Not Modified 140ms]
GET http://www.google-analytics.com/collect [HTTP/1.1 200 OK 33ms]
"Find US-Fremont" main_out.js:2
POST http://m.agar.io/ [HTTP/1.1 200 OK 243ms]
GET http://m.agar.io/info [HTTP/1.1 200 OK 490ms]
GET http://23.239.23.225:443/ [HTTP/1.1 101 Switching Protocols 278ms]
"Connecting to ws://23.239.23.225:443" main_out.js:2
"socket open" main_out.js:2
GET http://agar.io/skins/south%20korea.png [HTTP/1.1 304 Not Modified 32ms]
GET http://agar.io/skins/piccolo.png [HTTP/1.1 304 Not Modified 31ms]
===============================

So to me it look like it is not loading and i'm not sure why. I have also just tried this on 2 other computers (3 in total) and i'm still getting the same result of it not working

**Comment by DarkN3ss61** [comment]
Ok, if you have skype add me: DarkN3ss.com and i will give you my TeamViewer details on that

**Comment by Apostolique** [comment]
Fixed, firefox was out of date which made Greasemonkey not be the latest version. The old version couldn't run the script before page load.
